spring:
  datasource:
    url: jdbc:mysql://localhost:33066/hotel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hotel
    driverClassName: com.mysql.cj.jdbc.Driver
